# Basic Python

## 1. Split this string

In [17]:
s = "Hi there Sam!"

In [18]:
s = "Hi there Sam!"
txt=s.split()

print(txt)


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [13]:
planet = "Earth"
diameter = 12742

In [14]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [16]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [19]:
import numpy as np
array=np.zeros(10)
print(array)
array=np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [20]:
import numpy as np
array=np.zeros(10)
print(array)
array=np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [22]:
import numpy as np

print(np.arange(20,36,2))


[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [26]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [28]:
import pandas as pd
data = [['A', 100], ['B', 100], ['c', 100]]
df = pd.DataFrame(data, columns=['Name', 'Marks'])
df

Name  Marks
0    A    100
1    B    100
2    c    100

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [29]:
import pandas as pd
pd.date_range(start='1/1/2023',end='10/2/2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [30]:
import pandas as pd      
lists = [[1, 'Anu', 89], [2, 'Banu',76], [3, 'charu', 97]] 
data = pd.DataFrame(lists, columns =['sno','name','mark']) 
print(data )

   sno   name  mark
0    1    Anu    89
1    2   Banu    76
2    3  charu    97
